apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackoverflow-web
  namespace: stackoverflow
  labels:
    app.kubernetes.io/name: stackoverflow
spec:
  rules:
    - host: stackoverflow.apps.stackoverflow-dhmkov.clusters.intilitycloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stackoverflow-web
                port:
                  number: 80
  tls:
    - hosts:
        - stackoverflow.apps.stackoverflow-dhmkov.clusters.intilitycloud.com
