apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secrets
  namespace: stackoverflow
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false,Replace=false
  labels:
    app.kubernetes.io/name: stackoverflow
    app.kubernetes.io/component: database
type: Opaque
stringData:
  azurestorageaccountname: REPLACE_ME
  azurestorageaccountkey: REPLACE_ME
  sa-password: REPLACE_ME
